---

- name: get vmware tools latest download page
  ansible.windows.win_uri:
    url: "{{ vmware_tools_download_base_url }}"
    return_content: true
    validate_certs: false
  register: vmware_tools_latest_page
  until: vmware_tools_latest_page is success
  delay: 5
  retries: 30

- name: set vmware_tools_latest_install_file
  ansible.builtin.set_fact:
    vmware_tools_latest_install_file: "{{ vmware_tools_latest_page.content | regex_findall('A HREF=\"(.*)\">VMware-tools.*') }}"

- name: set vmware_tools_download_url
  ansible.builtin.set_fact:
    vmware_tools_download_url: "{{ vmware_tools_download_base_url }}{{ vmware_tools_latest_install_file[0] }}"
    vmware_tools_product_id: ''
  when: vmware_tools_latest_install_file|length
