---

- name: set become variables
  ansible.builtin.set_fact:
    become_user: '{{ ansible_user }}'
    become_pass: '{{ ansible_password }}'
  no_log: true

- block:
    - name: copy vmware tools to temp directory
      ansible.windows.win_get_url:
        url: '{{ vmware_tools_download_url }}'
        dest: '{{ temp_directory }}\{{ vmware_tools_download_url | urlsplit("path") | basename }}'
      register: download_vmware_tools
      until: download_vmware_tools is success
      delay: 3
      retries: 5

    - name: install vmware tools
      ansible.windows.win_package:
        path: '{{ download_vmware_tools.dest }}'
        arguments: /s /v "/qn reboot=r"
        state: present
      register: vmware_tools_install

  rescue:
    - block:
        - name: fail if vmware tools is not downloaded
          ansible.builtin.fail:
            msg: "no local copy of vmware tools"
          when: download_vmware_tools is not success

        - name: install vmware tools using win_shell module
          ansible.windows.win_shell: '{{ download_vmware_tools.dest }} /s /v "/qn reboot=r"'
          when: download_vmware_tools is success

        - name: check to see vmware tools is installed
          ansible.windows.win_stat:
            path: '{{ vmware_tools_install_location }}'
          register: check_vmware_tools_installation

        - name: fail if not installed
          ansible.builtin.fail:
            msg: "vmware tools is not installed.."
          when: not (check_vmware_tools_installation.stat.exists | default(true))

      rescue:
        - name: install with chocolatey
          chocolatey.chocolatey.win_chocolatey:
            name: vmware-tools
            state: present
          register: vmware_tools_install

  always:
    - name: remove downloaded file
      ansible.windows.win_file:
        path: '{{ temp_directory }}\{{ vmware_tools_download_url | urlsplit("path") | basename }}'
        state: absent
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ become_user | default(ansible_user) }}'
    ansible_become_pass: '{{ become_pass | default(ansible_password) }}'

- name: check to see vmware tools is installed
  ansible.windows.win_stat:
    path: '{{ vmware_tools_install_location }}'
  register: check_vmware_tools_installation

- name: fail if not installed
  ansible.builtin.fail:
    msg: "vmware tools is not installed.. well we tried..."
  when: not (check_vmware_tools_installation.stat.exists | default(true))
