---

- name: include architecture
  ansible.builtin.include_tasks: x86.yml
  when: (ansible_architecture2 | default('x86_64')) == 'x86_64'

- name: include architecture
  ansible.builtin.include_tasks: arm.yml
  when: (ansible_architecture2 | default('x86_64')) == 'arm64'
