---

# This is needed on 2008
# See: https://kb.vmware.com/s/article/78708
- include_tasks: security_update_2008.yml
  when: "'Windows Server 2008' in ansible_distribution or 'Windows 7' in ansible_distribution"

- name: set become variables
  set_fact:
    become_user: '{{ ansible_user }}'
    become_pass: '{{ ansible_password }}'
  no_log: True

- block:
    - include_tasks: find_latest.yml
      when: vmware_tools_find_latest

    - name: install vmware tools
      win_package:
        path: '{{ vmware_tools_download_url }}'
        product_id: '{{ vmware_tools_product_id }}'
        arguments: /s /v "/qn reboot=r"
        state: present
      register: vmware_tools_install
  rescue:
    - name: copy vmware tools to temp directory
      win_get_url:
        url: '{{ vmware_tools_download_url }}'
        dest: '{{ temp_directory }}\{{ vmware_tools_download_url | urlsplit("path") | basename }}'
      register: download_vmware_tools
      until: download_vmware_tools is success
      delay: 3
      retries: 5

    - name: install vmware tools using win_shell module
      win_shell: '{{ download_vmware_tools.dest }} /s /v "/qn reboot=r"'
      when: download_vmware_tools is success

    - name: remove temporary file
      win_file:
        path: '{{ temp_directory }}\{{ vmware_tools_download_url | urlsplit("path") | basename }}'
        state: absent
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: '{{ become_user | default(ansible_user) }}'
    ansible_become_pass: '{{ become_pass | default(ansible_password) }}'

- name: check to see vmware tools is installed (1/3)
  win_stat:
    path: 'C:\Program Files\VMware\VMware Tools\vmtoolsd.exe'
  register: vmware_tools_install

- block:
    - name: pending reboot
      win_reboot:
      when: vmware_tools_install.reboot_required | default(true)

    - name: install vmware tools (retry)
      win_package:
        path: '{{ vmware_tools_download_url }}'
        product_id: '{{ vmware_tools_product_id }}'
        arguments: /s /v "/qn reboot=r"
        state: present

    - name: check to see vmware tools is installed (2/3)
      win_stat:
        path: 'C:\Program Files\VMware\VMware Tools\vmtoolsd.exe'
      register: vmware_tools_install_2

    - block:
        - name: install with chocolatey
          win_chocolatey:
            name: vmware-tools
            state: present

        - name: check to see vmware tools is installed (3/3)
          win_stat:
            path: 'C:\Program Files\VMware\VMware Tools\vmtoolsd.exe'
          register: vmware_tools_install_3

        - name: fail if not installed
          fail:
            msg: "vmware tools is not installed.. well we tried..."
          when: not (vmware_tools_install_3.stat.exists | default(true))
      when: not (vmware_tools_install_2.stat.exists | default(true))
  when: not (vmware_tools_install.stat.exists | default(true))

# This is needed on 2008 for vmware customization to be successful
# See: https://kb.vmware.com/s/article/66765
- name: install the visual C libraries
  win_package:
    path: https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x86.exe
    product_id: '{9BE518E6-ECC6-35A9-88E4-87755C07200F}'
    arguments: '/qb!'
  when: "'Windows Server 2008' in ansible_distribution or 'Windows 7' in ansible_distribution"

- name: reboot after installation
  win_reboot: