---

- name: set become variables
  set_fact:
    become_user: '{{ ansible_user }}'
    become_pass: '{{ ansible_password }}'
  no_log: True

- block:

    - name: install vmware tools
      win_package:
        path: '{{ vmware_tools_download_url }}'
        product_id: '{{ vmware_tools_product_id }}'
        arguments: '/s /v "/qn reboot=r"'
        state: present

  rescue:
    - name: copy vmware tools to temp directory
      win_get_url:
        url: '{{ vmware_tools_download_url }}'
        dest: '{{ ansible_env.TEMP }}\{{ vmware_tools_download_url | urlsplit("path") | basename }}'
      register: download_vmware_tools
      until: download_vmware_tools is success
      delay: 3
      retries: 5

    - name: install vmware tools using win_shell module
      win_shell: '{{ download_vmware_tools.dest }} /s /v "/qn reboot=r"'
      when: download_vmware_tools is success

    - name: remove temporary file
      win_file:
        path: '{{ ansible_env.TEMP }}\{{ vmware_tools_download_url | urlsplit("path") | basename }}'
        state: absent
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: '{{ become_user | default(ansible_user) }}'
    ansible_become_pass: '{{ become_pass | default(ansible_password) }}'

- name: check to see vmware tools is installed
  win_stat:
    path: 'C:\Program Files\VMware\VMware Tools\vmtoolsd.exe'
  register: vmware_tools_install

- name: install with chocolatey
  win_chocolatey:
    name: vmware-tools
    state: present
  when: not vmware_tools_install.stat.exists

- name: check to see vmware tools is installed (2nd time)
  win_stat:
    path: 'C:\Program Files\VMware\VMware Tools\vmtoolsd.exe'
  register: vmware_tools_install_2

- name: fail if not installed
  fail:
    msg: "vmware tools is not installed.. well we tried..."
  when: not vmware_tools_install_2.stat.exists

# This is needed on 2008 for vmware customization to be successful
# See: https://kb.vmware.com/s/article/66765
- name: install the visual C libraries
  win_package:
    path: https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x86.exe
    product_id: '{9BE518E6-ECC6-35A9-88E4-87755C07200F}'
    arguments: '/qb!'
  when: "'Windows Server 2008' in ansible_distribution"

- name: reboot after installation
  win_reboot: