---

- block:
    - name: ensure Windows ADK with DISM is installed
      ansible.windows.win_package:
        path: https://go.microsoft.com/fwlink/?linkid=873065 # version 10.0.17134.0
        product_id: '{{ _product_id }}'
        expected_return_code:
          - 0
          - 3010
        arguments: "{{ _arguments | join(' ') }}"
      notify:
        - get Windows ADK uninstall command
        - uninstall Windows ADK

  rescue:
    - block:
        - name: download DISM
          win_get_url:
            url: https://go.microsoft.com/fwlink/?linkid=873065
            dest: '{{ temp_directory }}\adksetup.exe'
          register: download_dism
          retries: 5
          delay: 5
          until: download_dism is success

        - name: ensure Windows ADK with DISM is installed
          ansible.windows.win_package:
            path: '{{ temp_directory }}\adksetup.exe' # version 10.0.17134.0
            product_id: '{{ _product_id }}'
            expected_return_code:
              - 0
              - 3010
            arguments: "{{ _arguments | join(' ') }}"
          notify:
            - get Windows ADK uninstall command
            - uninstall Windows ADK

      rescue:
        - name: ensure Windows ADK with DISM is installed (chocolatey)
          chocolatey.chocolatey.win_chocolatey:
            name: windows-adk-deploy
            state: present
            version: 10.0.17134.0
          register: install_windows_adk_deploy
          notify: ensure Windows ADK with DISM is removed

  vars:
    _product_id: '{d794748d-72e9-45d7-9ab7-83d6c4c80f7f}'
    _arguments:
      - /quiet
      - /norestart
      - /features {{ _features | join(' ') }}
    _features:
      - OptionId.DeploymentTools
      - OptionId.WindowsPreinstallationEnvironment
      - OptionId.ImagingAndConfigurationDesigner
      - OptionId.UserStateMigrationTool

- block:
    - name: download hotfix
      ansible.windows.win_get_url:
        url: '{{ win_61_security_hot_fix.url }}'
        dest: '{{ temp_directory }}\{{ win_61_security_hot_fix.file }}'
      register: download_hotfix
      until: download_hotfix is success
      delay: 3
      retries: 5

    - name: apply hotfix (ps3)
      ansible.builtin.include_tasks: hotfix_ps3.yml
      when: ansible_powershell_version is version('3', '==')
      vars:
        hotfix_download: "{{ win_61_security_hot_fix }}"
        hotfix_temp_directory: "{{ temp_directory }}"

    - block:
        - name: apply hotfix (ps4)
          ansible.builtin.include_tasks: hotfix_ps4.yml
      rescue:
        - name: apply hotfix (ps3)
          ansible.builtin.include_tasks: hotfix_ps3.yml
      when: ansible_powershell_version is version('4', '>=')
      vars:
        hotfix_download: "{{ win_61_security_hot_fix }}"
        hotfix_temp_directory: "{{ temp_directory }}"

    - name: reboot
      ansible.windows.win_reboot:
      when:
        - hotfix_install is defined
        - hotfix_install is changed
  always:
    - name: ensure hotfix file is removed
      ansible.windows.win_file:
        path: '{{ temp_directory }}\{{ win_61_security_hot_fix.file }}'
        state: absent
